UICCAI-1390: test result fixes
Nuvalence/dialogflow-cx-tools pull request #57
Opened 2024-02-15 18:31 UTC by gteng-nuvalence

## Describe your changes

* Reworked result collection for DFCX test builder-based tests
  * Test assessment now forced to run in singular thread for collection purposes
* Added more detailed logs for result counts/summary

## Issue ticket number and link

https://dol-ewf.atlassian.net/browse/UICCAI-1390

## Testing

Run the following command:
```
./gradlew cx-test:run --args src/main/resources/default.properties 
```
where `default.properties` contains the desired properties, such as the following:
```
credentialsUrl=file:///path/to/credentials/file
agentPath=projects/<project>/locations/<location>/agents/<agentPath>
dfcxEndpoint=dialogflow.googleapis.com:443
dfcxTagFilter=!#Submission
testPackage=io.nuvalence.cx.tools.cxtest
```

Example spreadsheet output found [here](https://docs.google.com/spreadsheets/d/1TCbqDyM8F_lql6fuKTY25DryPFinqphfoQ9V-f1trQM/edit#gid=0).

Example terminal output:
<img width="945" alt="image" src="https://github.com/Nuvalence/dialogflow-cx-tools/assets/106610715/ddfb267b-3420-4b74-8a30-8a39e19a00e1">

2024-02-20 20:38 UTC, jimmie-potts requested changes
The pass/fail results on the summary page are not adding up to the total number of tests:
![image](https://github.com/Nuvalence/dialogflow-cx-tools/assets/49133657/de0fb277-b68b-4e27-b43d-3acb6872f230)

2024-02-20 20:38 UTC, jimmie-potts commented on cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/extension/DFCXTestBuilderExtension.kt
> +
Let's update the console output to only output the results that are also found in the summary page of the spreadsheet, 1 set of Tests Run, Tests Passed, and Tests Failed.
![image](https://github.com/Nuvalence/dialogflow-cx-tools/assets/49133657/e4e925b0-1c91-45a1-8011-c706f922f10c)

2024-02-22 14:16 UTC, jimmie-potts commented
> @jimmie-potts re: [#57 (review)](https://github.com/Nuvalence/dialogflow-cx-tools/pull/57#pullrequestreview-1891532889)
> 
> Please provide a sample test filter (if applicable) for reproduction purposes, and/or a link to your test results spreadsheet -- the result counts were consistent in my own testing, so I'd like to explore certain possibilities (e.g. potential race conditions from the test result pullback request, or unique error conditions unaccounted for in my own tests) as part of triage.

I ran the tests against the p2 dev agent with no filters. However, I've been unable to reproduce so I will chalk this one up to tester error on my part. So no worries and addressing the count in the spreadsheet.

2024-02-23 19:42 UTC, gteng-nuvalence commented on cx-test/src/main/kotlin/io/nuvalence/cx/tools/cxtest/extension/DFCXTestBuilderExtension.kt
> +
Amended:
<img width="790" alt="image" src="https://github.com/Nuvalence/dialogflow-cx-tools/assets/106610715/70085ef3-01a8-471b-b352-f16f8b26fa5b">

2024-02-26 14:25 UTC, jimmie-potts approved these changes

2024-02-26 15:23 UTC, merged