UICCAI-1510: add command to create zip and restore to DFCX agent
Nuvalence/dialogflow-cx-tools pull request #64
Opened 2024-03-12 15:00 UTC by nuvalencenate

This PR does a couple things:
- moves the agent generation logic to the generator directory and structures the cx-agent folder after cx-phrases and cx-test, making the argument `generate` indicate agent generation (while maintaining agent generation functionality)
- adds `zip-restore` command to zip an agent directory and optionally restore it to a DFCX agent

Details are added in the root README and in the cx-agent README

2024-03-13 16:23 UTC, jimmie-potts approved these changes

2024-03-13 16:25 UTC, jimmie-potts requested changes

2024-03-13 16:25 UTC, jimmie-potts commented on cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/compressor/Compressor.kt
> +        val agentBytes = Files.readAllBytes(Paths.get(zipFile))
Let's add error handling here in case the file cannot be found. I originally just had a folder path here and not the zip file, but the error message wasn't clear what the problem was.

2024-03-13 21:15 UTC, nuvalencenate commented on cx-agent/src/main/kotlin/io/nuvalence/cx/tools/cxagent/compressor/Compressor.kt
> +        val agentBytes = Files.readAllBytes(Paths.get(zipFile))
Updated to catch any exception instead of just the ApiException and added some details to the error message - let me know if that looks like it would be more helpful!

2024-03-15 11:51 UTC, jimmie-potts approved these changes

2024-03-15 11:51 UTC, merged